/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    articles: Article;
    'comparison-articles': ComparisonArticle;
    citations: Citation;
    'quran-verses': QuranVerse;
    'bible-verses': BibleVerse;
    'glossary-terms': GlossaryTerm;
    'source-library-categories': SourceLibraryCategory;
    'source-library-items': SourceLibraryItem;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'comparison-articles': ComparisonArticlesSelect<false> | ComparisonArticlesSelect<true>;
    citations: CitationsSelect<false> | CitationsSelect<true>;
    'quran-verses': QuranVersesSelect<false> | QuranVersesSelect<true>;
    'bible-verses': BibleVersesSelect<false> | BibleVersesSelect<true>;
    'glossary-terms': GlossaryTermsSelect<false> | GlossaryTermsSelect<true>;
    'source-library-categories': SourceLibraryCategoriesSelect<false> | SourceLibraryCategoriesSelect<true>;
    'source-library-items': SourceLibraryItemsSelect<false> | SourceLibraryItemsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ar') | ('en' | 'ar')[];
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'ar';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'owner' | 'reviewer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  subtitle: string;
  slug: string;
  category:
    | 'the-quran-and-the-bible'
    | 'jesus-in-islam-and-christianity'
    | 'preservation'
    | 'difficult-questions'
    | 'scientific-signs'
    | 'religious-history'
    | 'historical-evidence'
    | 'tawhid-and-the-trinity'
    | 'salvation-and-purpose-of-life'
    | 'prophecies'
    | 'war-and-violence'
    | 'women'
    | 'questions'
    | 'glossary'
    | 'sources';
  audienceLevel: 'beginner' | 'intermediate' | 'deep-study';
  summary: string;
  tags?:
    | (
        | 'Jesus'
        | 'Preservation'
        | 'Theology'
        | 'History'
        | 'Scripture'
        | 'Questions'
        | 'Science'
        | 'Sources'
        | 'Purpose'
        | 'Prophecy'
      )[]
    | null;
  /**
   * Published requires every linked citation to be verified (enforced by the publish gate).
   */
  status: 'draft' | 'reviewed' | 'published';
  lastUpdated: string;
  sections: {
    /**
     * Anchor id, e.g. beginner-summary.
     */
    sectionId: string;
    title: string;
    kind: 'summary' | 'scripture' | 'interpretation' | 'history' | 'argument' | 'sources' | 'notes';
    body: string;
    citations?: (number | Citation)[] | null;
    id?: string | null;
  }[];
  /**
   * Citations listed in the article's Sources section.
   */
  citations?: (number | Citation)[] | null;
  relatedArticles?: (number | Article)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "citations".
 */
export interface Citation {
  id: number;
  /**
   * Stable key used by seed data and cross-references, e.g. source-pending-quran-translation.
   */
  citationKey: string;
  type:
    | 'quran'
    | 'bible'
    | 'hadith'
    | 'tafsir'
    | 'christian-commentary'
    | 'academic'
    | 'book'
    | 'article'
    | 'manuscript'
    | 'other';
  title: string;
  author?: string | null;
  publisher?: string | null;
  year?: number | null;
  url?: string | null;
  note?: string | null;
  /**
   * Do not mark verified until the exact source has been checked.
   */
  status: 'pending' | 'verified';
  verifiedBy?: string | null;
  verifiedDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comparison-articles".
 */
export interface ComparisonArticle {
  id: number;
  /**
   * Must match the slug of the base article record.
   */
  slug: string;
  /**
   * Published requires every linked citation and scripture record to be verified (enforced by the publish gate).
   */
  status: 'draft' | 'reviewed' | 'published';
  mainQuestion: string;
  beginnerSummary: string;
  quranicPerspective: string;
  biblicalPerspective: string;
  historicalContext: string;
  christianInterpretation: string;
  islamicResponse: string;
  keyDifferences?:
    | {
        difference: string;
        id?: string | null;
      }[]
    | null;
  commonObjections?:
    | {
        objection: string;
        response: string;
        id?: string | null;
      }[]
    | null;
  respectfulConclusion: string;
  quranVerses?: (number | QuranVerse)[] | null;
  bibleVerses?: (number | BibleVerse)[] | null;
  sources?: (number | Citation)[] | null;
  relatedTopics?:
    | {
        topic: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quran-verses".
 */
export interface QuranVerse {
  id: number;
  surahName: string;
  surahNumber: number;
  ayahNumber: number;
  /**
   * Verified Arabic text only. Placeholders must clearly say [VERIFIED ARABIC QURAN TEXT PENDING].
   */
  arabic: string;
  translation: string;
  translator: string;
  reference: string;
  arabicTafsirNote?: string | null;
  notes?: string | null;
  /**
   * Scripture text must come from a verified source (e.g. the Tanzil / King Fahd Complex Quran text, a licensed Bible translation) before it can be marked verified.
   */
  status: 'pending' | 'verified';
  /**
   * Where the exact text was taken from, once verified.
   */
  sourceAttribution?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bible-verses".
 */
export interface BibleVerse {
  id: number;
  book: string;
  chapter: number;
  /**
   * Single verse or range, e.g. 3 or 3-5.
   */
  verse: string;
  text: string;
  arabicText?: string | null;
  arabicSource?: string | null;
  version: string;
  reference: string;
  notes?: string | null;
  /**
   * Scripture text must come from a verified source (e.g. the Tanzil / King Fahd Complex Quran text, a licensed Bible translation) before it can be marked verified.
   */
  status: 'pending' | 'verified';
  /**
   * Where the exact text was taken from, once verified.
   */
  sourceAttribution?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "glossary-terms".
 */
export interface GlossaryTerm {
  id: number;
  term: string;
  pronunciation?: string | null;
  definition: string;
  category:
    | 'Jesus'
    | 'Preservation'
    | 'Theology'
    | 'History'
    | 'Scripture'
    | 'Questions'
    | 'Science'
    | 'Sources'
    | 'Purpose'
    | 'Prophecy';
  relatedTerms?: (number | GlossaryTerm)[] | null;
  citations?: (number | Citation)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "source-library-categories".
 */
export interface SourceLibraryCategory {
  id: number;
  title: string;
  description: string;
  /**
   * Display order on the /sources page.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "source-library-items".
 */
export interface SourceLibraryItem {
  id: number;
  title: string;
  type:
    | 'quran'
    | 'bible'
    | 'hadith'
    | 'tafsir'
    | 'christian-commentary'
    | 'academic'
    | 'book'
    | 'article'
    | 'manuscript'
    | 'other';
  category: number | SourceLibraryCategory;
  authorOrPublisher?: string | null;
  year?: number | null;
  url?: string | null;
  notes: string;
  /**
   * Do not add authors, publishers, years, URLs, or manuscript details unless they have been checked.
   */
  status: 'pending' | 'verified';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'comparison-articles';
        value: number | ComparisonArticle;
      } | null)
    | ({
        relationTo: 'citations';
        value: number | Citation;
      } | null)
    | ({
        relationTo: 'quran-verses';
        value: number | QuranVerse;
      } | null)
    | ({
        relationTo: 'bible-verses';
        value: number | BibleVerse;
      } | null)
    | ({
        relationTo: 'glossary-terms';
        value: number | GlossaryTerm;
      } | null)
    | ({
        relationTo: 'source-library-categories';
        value: number | SourceLibraryCategory;
      } | null)
    | ({
        relationTo: 'source-library-items';
        value: number | SourceLibraryItem;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  slug?: T;
  category?: T;
  audienceLevel?: T;
  summary?: T;
  tags?: T;
  status?: T;
  lastUpdated?: T;
  sections?:
    | T
    | {
        sectionId?: T;
        title?: T;
        kind?: T;
        body?: T;
        citations?: T;
        id?: T;
      };
  citations?: T;
  relatedArticles?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comparison-articles_select".
 */
export interface ComparisonArticlesSelect<T extends boolean = true> {
  slug?: T;
  status?: T;
  mainQuestion?: T;
  beginnerSummary?: T;
  quranicPerspective?: T;
  biblicalPerspective?: T;
  historicalContext?: T;
  christianInterpretation?: T;
  islamicResponse?: T;
  keyDifferences?:
    | T
    | {
        difference?: T;
        id?: T;
      };
  commonObjections?:
    | T
    | {
        objection?: T;
        response?: T;
        id?: T;
      };
  respectfulConclusion?: T;
  quranVerses?: T;
  bibleVerses?: T;
  sources?: T;
  relatedTopics?:
    | T
    | {
        topic?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "citations_select".
 */
export interface CitationsSelect<T extends boolean = true> {
  citationKey?: T;
  type?: T;
  title?: T;
  author?: T;
  publisher?: T;
  year?: T;
  url?: T;
  note?: T;
  status?: T;
  verifiedBy?: T;
  verifiedDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quran-verses_select".
 */
export interface QuranVersesSelect<T extends boolean = true> {
  surahName?: T;
  surahNumber?: T;
  ayahNumber?: T;
  arabic?: T;
  translation?: T;
  translator?: T;
  reference?: T;
  arabicTafsirNote?: T;
  notes?: T;
  status?: T;
  sourceAttribution?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bible-verses_select".
 */
export interface BibleVersesSelect<T extends boolean = true> {
  book?: T;
  chapter?: T;
  verse?: T;
  text?: T;
  arabicText?: T;
  arabicSource?: T;
  version?: T;
  reference?: T;
  notes?: T;
  status?: T;
  sourceAttribution?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "glossary-terms_select".
 */
export interface GlossaryTermsSelect<T extends boolean = true> {
  term?: T;
  pronunciation?: T;
  definition?: T;
  category?: T;
  relatedTerms?: T;
  citations?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "source-library-categories_select".
 */
export interface SourceLibraryCategoriesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "source-library-items_select".
 */
export interface SourceLibraryItemsSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  category?: T;
  authorOrPublisher?: T;
  year?: T;
  url?: T;
  notes?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}